version: "3.1"

services:
    todo-postgres:
        container_name: todo-postgres
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=none
            - POSTGRES_DB=todoapp
        ports:
            - "5000:5432"
    todo-backend:
        container_name: todo-backend
        image: todo-backend
        depends_on:
            - todo-postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=none
            - FRONTEND_URL=https://localhost
            - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-postgres:5432/todoapp
            - KEY_STORE_PASSWORD=none
        build:
            context: todo-app-backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    todo-frontend:
        container_name: todo-frontend
        image: todo-frontend
        depends_on:
            - todo-backend
        build:
            context: todo-app-frontend
            dockerfile: Dockerfile
        ports:
            - "4200:443"
    todo-nginx:
        container_name: todo-nginx
        image: todo-nginx
        build:
            context: todo-app-nginx
            dockerfile: Dockerfile
        depends_on:
            - todo-frontend
        ports:
            - "443:443"
