version: "3.1"

services:
    todo-app-frontend:
        container_name: todo-app-frontend
        image: todo-app-frontend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4200:80"
