server:
    port: 8080

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${_POSTGRES_USER}
        password: ${_POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

security:
    jwt:
        expiration-time: 86400000
        refresh-time: 604800000
        encoding-key: 25442A472D4B6150645367566B597033733676397924423F4528482B4D625165
