server:
    port: 8080

    server-header: ""

    ssl:
        key-store-type: PKCS12
        key-store: classpath:server.p12
        key-store-password: ${KEY_STORE_PASSWORD}
        enabled: true

    http2:
        enabled: true

        compression:
            enabled: true
            mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
            min-response-size: 1024

logging:
    level:
        root: INFO
        org.springframework.web: INFO

frontend:
    url: ${FRONTEND_URL}

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    security:
        jwt:
            expiration-time: 86400000
            refresh-time: 604800000
