version: "3.1"

services:
    todo-postgres:
        container_name: todo-postgres
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=none
            - POSTGRES_DB=todoapp
        ports:
            - "5000:5432"
    todo-app-backend:
        container_name: todo-app-backend
        image: todo-app-backend
        depends_on:
            - todo-postgres
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-postgres:5432/todoapp
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
